export const siteConfig = {
    locales: ['en', 'th'],
    defaultLocale: 'en',
    navMenu: [{
        title: "home",
        href: "/",
        image: "/images/nav/nav_home.png",
        emoji: "🏠"
    },
    {
        title: "AphasiaTalk",
        href: "/",
        image: "/images/logo.png",
        emoji: "🏠"
    },
    {
        title: "settings",
        href: "/settings",
        image: "/images/nav/nav_info.png",
        emoji: "⚙️"
    }
]
}

export const mainMenu =  [
    {
        title: "iwant",
        img: "/images/menu/wave.png",
        href: "/iwant",
        prefix: "I want",
        list: [
            { "title": "medicine"},
            { "title": "comb"}, 
            { "title": "drawing"},
            { "title": "exercise"},
            { "title": "listen to music"},
            { "title": "hair wash"},
            { "title": "cane"},
            { "title": "nail cut"},
            { "title": "powder"},
            { "title": "read"},
            { "title": "shower"},
            { "title": "sit"},
            { "title": "eat"},
            { "title": "shopping"},
            { "title": "watch tv"},
            { "title": "wheelchair"},
            { "title": "walk"},
            { "title": "toilet"},
            { "title": "teeth brush"},
            { "title": "talk"},
            { "title": "sleep"},
            { "title": "go out"},
            { "title": "pee"},
            { "title": "poop"},
        ]
    },
    {
        title: "ifeel",
        img: "/images/menu/feeling.png",
        href: "/ifeel",
        list: [
            { "title": "angry"},
            { "title": "cold"},
            { "title": "hot"},
            { "title": "happy"},
            { "title": "hungry"},
            { "title": "sad"},
            { "title": "scared"},
            { "title": "itchy"},
            { "title": "sleepy"},
            { "title": "stress"},
            { "title": "tired"},
            { "title": "arm pain"},
            { "title": "back pain"},
            { "title": "chest pain"},
            { "title": "ear pain"},
            { "title": "bottom pain"},
            { "title": "elbow pain"},
            { "title": "eye pain"},
            { "title": "feet pain"},
            { "title": "hand pain"},
            { "title": "head pain"},
            { "title": "knee pain"},
            { "title": "leg pain"},
            { "title": "neck pain"},
            { "title": "shoulder pain"},
            { "title": "stomach pain"},
            { "title": "nose pain"},
            { "title": "hip pain"},
            { "title": "teeth pain"},    
        ]
    },
    {
        title: "food",
        img: "/images/menu/cutlery.png",
        href: "/food",
        list: [
            { "title": "apple", "group": "fruit" },
            { "title": "cantaloop", "group": "fruit" },
            { "title": "rose apple", "group": "fruit" },
            { "title": "dragonfruit", "group": "fruit" },
            { "title": "durian", "group": "fruit" },
            { "title": "gauva", "group": "fruit" },
            { "title": "pumpkin", "group": "fruit" },
            { "title": "banana", "group": "fruit" },
            { "title": "longan", "group": "fruit" },
            { "title": "lynchee", "group": "fruit" },
            { "title": "longkong", "group": "fruit" },
            { "title": "papaya", "group": "fruit" },
            { "title": "mango", "group": "fruit" },
            { "title": "mangostein", "group": "fruit" },
            { "title": "pineapple", "group": "fruit" },
            { "title": "strawberry", "group": "fruit" },
            { "title": "tamarind", "group": "fruit" },
            { "title": "watermelon", "group": "fruit" },
            { "title": "taro", "group": "fruit" },
            { "title": "orange", "group": "fruit" },
            { "title": "grape", "group": "fruit" },
            { "title": "rambutan", "group": "fruit" },
            { "title": "custard apple", "group": "fruit" },
            { "title": "jackfruit", "group": "fruit" },
            // Food
            { "title": "จับฉ่าย", "group": "curry" },
            { "title": "แกงจืดเต้าหู้", "group": "curry" },
            { "title": "แกงเขียวหวาน", "group": "curry" },
            { "title": "แกงมะระ", "group": "curry" },
            { "title": "แกงส้มชะอม", "group": "curry" },
            { "title": "แกงเหลืองหมู", "group": "curry" },
            { "title": "ไข่พะโล้", "group": "curry" },
            { "title": "แกงมัสมั่น", "group": "curry" },
            { "title": "แกงเห็ด", "group": "curry" },
            { "title": "พะแนงหมู", "group": "curry" },
            { "title": "โป๊ะแตก", "group": "curry" },
            { "title": "ซุปไก่", "group": "curry" },
            { "title": "ต้มยำกุ้ง", "group": "curry" },
            { "title": "ต้มแซบ", "group": "curry" },
            { "title": "บะหมี่หมูแดง", "group": "main" },
            { "title": "บะหมี่หมูกรอบ", "group": "main" },
            { "title": "เบอร์เกอร์เนื้อ", "group": "main" },
            { "title": "สเต็กเนื้อ", "group": "main" },
            { "title": "ก๋วยเตี๋ยวไก่", "group": "main" },
            { "title": "เฝอ", "group": "main" },
            { "title": "ไส้กรอกเยอรมัน", "group": "main" },
            { "title": "โจ๊ก", "group": "main" },
            { "title": "ขนมจีน", "group": "main" },
            { "title": "ข้าวไข่เจียว", "group": "main" },
            { "title": "ข้าวไข่ข้นกุ้ง", "group": "main" },
            { "title": "ข้าวไก่ย่าง", "group": "main" },
            { "title": "ข้าวขาหมู", "group": "main" },
            { "title": "ข้าวคลุกกะปิ", "group": "main" },
            { "title": "ข้าวหมูทอดราดไข่", "group": "main" },
            { "title": "ข้าวมันไก่", "group": "main" },
            { "title": "ข้าวเหนียวหมูปิ้ง", "group": "main" },
            { "title": "ข้าวหน้ากะเพราหมูทอด", "group": "main" },
            { "title": "ข้าวหน้าเป็ด", "group": "main" },
            { "title": "ข้าวหน้าปลาดิบ", "group": "main" },
            { "title": "ข้าวหน้าแซลมอน", "group": "main" },
            { "title": "ข้าวผัดหมู", "group": "main" },
            { "title": "ข้าวผัดแกงเขียวหวาน", "group": "main" },
            { "title": "ข้าวผัดกุ้ง", "group": "main" },
            { "title": "ข้าวผัดปู", "group": "main" },
            { "title": "ข้าวผัดสับปะรด", "group": "main" },
            { "title": "ข้าวราดกระเพราไข่ดาว", "group": "main" },
            { "title": "ข้าวต้มหมู", "group": "main" },
            { "title": "ข้าวต้มปลา", "group": "main" },
            { "title": "เคบับ", "group": "main" },
            { "title": "ก๋วยเตี๋ยวเซี่ยงไฮ้", "group": "main" },
            { "title": "ก๋วยจั๊บ", "group": "main" },
            { "title": "ลักซา", "group": "main" },
            { "title": "มาม่า", "group": "main" },
            { "title": "แหนมเนือง", "group": "main" },
            { "title": "ก๋วยเตี๋ยว", "group": "main" },
            { "title": "น้ำตก", "group": "main" },
            { "title": "พาสต้า", "group": "main" },
            { "title": "พิซซ่า", "group": "main" },
            { "title": "เบอร์เกอร์หมู", "group": "main" },
            { "title": "สเต็กหมู", "group": "main" },
            { "title": "ผัดมาม่า", "group": "main" },
            { "title": "ผัดหมี่", "group": "main" },
            { "title": "ผัดซีอิ๊ว", "group": "main" },
            { "title": "ผัดไทย", "group": "main" },
            { "title": "ราเมน", "group": "main" },
            { "title": "ซาชิมิ", "group": "main" },
            { "title": "ยำทะเลเย็น", "group": "main" },
            { "title": "ซูชิ", "group": "main" },
            { "title": "เตี๋ยวต้มยำ", "group": "main" },
            { "title": "ฮะเก๋า", "group": "steam" },
            { "title": "ห่อหมก", "group": "steam" },
            { "title": "หอยแมลงภู่อบกระเทียม", "group": "steam" },
            { "title": "หอยแมลงภู่อบ", "group": "steam" },
            { "title": "ไข่เจียวลาวา", "group": "steam" },
            { "title": "ไข่ต้ม", "group": "steam" },
            { "title": "ขนมจีบ", "group": "steam" },
            { "title": "ก๋วยเตี๋ยวหลอด", "group": "steam" },
            { "title": "ขนมกุยช่าย", "group": "steam" },
            { "title": "ปลานึ่งซีอิ๊ว", "group": "steam" },
            { "title": "ปูนึ่ง", "group": "steam" },
            { "title": "ซาลาเปา", "group": "steam" },
            { "title": "ผักโขมอบชีส", "group": "steam" },
            { "title": "ไก่ผัดขิง", "group": "stir fry" },
            { "title": "ไก่ผัดหน่อไม้", "group": "stir fry" },
            { "title": "กระเพราหมูสับ", "group": "stir fry" },
            { "title": "หมูผัดขิง", "group": "stir fry" },
            { "title": "หมูผัดน้ำมันหอย", "group": "stir fry" },
            { "title": "ผัดผักบุ้ง", "group": "stir fry" },
            { "title": "ปลาดุกฟู", "group": "stir fry" },
            { "title": "ปลาราดพริก", "group": "stir fry" },
            { "title": "ผัดฉ่า", "group": "stir fry" },
            { "title": "ผัดคะน้า", "group": "stir fry" },
            { "title": "ผัดผักรวม", "group": "stir fry" },
            { "title": "ผัดผักกรูมพี่", "group": "stir fry" },
            { "title": "ผัดผงกะหรี่", "group": "stir fry" },
            { "title": "ผัดถั่วหมู", "group": "stir fry" },
            { "title": "ผัดวุ้นเส้น", "group": "stir fry" },
            { "title": "เต้าหู้ผัดพริก", "group": "stir fry" },
            { "title": "บัวลอย", "group": "dessert" },
            { "title": "เฉาก๊วย", "group": "dessert" },
            { "title": "ขนมครก", "group": "dessert" },
            { "title": "ขนมต้ม", "group": "dessert" },
            { "title": "ข้าวเหนียวมะม่วง", "group": "dessert" },
            { "title": "กวยบัวดึง", "group": "dessert" },
            { "title": "ลอดช่อง", "group": "dessert" },
            { "title": "เมลอนกะทิ", "group": "dessert" },
            { "title": "ขนมไทยรวม", "group": "dessert" },
            { "title": "ซาหลิม", "group": "dessert" },
            { "title": "บัวลอยเผือก", "group": "dessert" },
            { "title": "เต้าฮวย", "group": "dessert" },
            { "title": "ทับทิมกรอบ", "group": "dessert" },
            { "title": "เบคอนทอด", "group": "fried" },
            { "title": "ห่อจ้อ", "group": "fried" },
            { "title": "แก้วทอด", "group": "fried" },
            { "title": "แก้วซ่า", "group": "fried" },
            { "title": "ไข่ดาว", "group": "fried" },
            { "title": "ไข่เจียว", "group": "fried" },
            { "title": "ไข่นกกระทาทอด", "group": "fried" },
            { "title": "ไข่ทอด", "group": "fried" },
            { "title": "ไก่ย่าง", "group": "fried" },
            { "title": "กุ้งเผา", "group": "fried" },
            { "title": "คอหมูย่าง", "group": "fried" },
            { "title": "หมึกทอด", "group": "fried" },
            { "title": "นักเก็ต", "group": "fried" },
            { "title": "ปลาทอด", "group": "fried" },
            { "title": "เปลือกหอยย่าง", "group": "fried" },
            { "title": "เสือร้องไห้", "group": "fried" },
            { "title": "ทอดมัน", "group": "fried" },
            { "title": "ยำกุ้งน้ำปลา", "group": "salad" },
            { "title": "ลาบหมู", "group": "salad" },
            { "title": "หมูมะนาว", "group": "salad" },
            { "title": "น้ำพริกกะปิ", "group": "salad" },
            { "title": "น้ำพริกปลาทู", "group": "salad" },
            { "title": "น้ำพริกไข่ปู", "group": "salad" },
            { "title": "น้ำตกหมู", "group": "salad" },
            { "title": "ปลาลวก", "group": "salad" },
            { "title": "สลัดไก่", "group": "salad" },
            { "title": "สลัดปลาดอร์", "group": "salad" },
            { "title": "สลัดผัก", "group": "salad" },
            { "title": "ตับวอน", "group": "salad" },
            { "title": "ตำข้าวโพด", "group": "salad" },
            { "title": "ตำปลาร้า", "group": "salad" },
            { "title": "ตำไทย", "group": "salad" },
            { "title": "ยำรวมมิตรกุ้ง", "group": "salad" },
            { "title": "ยำแซลมอน", "group": "salad" },
            { "title": "ยำวุ้นเส้น", "group": "salad" }
    ]
    },
    {
        title: "beverage",
        img: "/images/menu/soda.png",
        href: "/beverage",
        list: [
            { "title": "ชาเขียวเย็น" },
            { "title": "ชาเย็น" },
            { "title": "โค้ก" },
            { "title": "กาแฟเย็น" },
            { "title": "เก๊กฮวย" },
            { "title": "น้ำใบบัวบก" },
            { "title": "น้ำกระเจี๊ยบ" },
            { "title": "น้ำมะนาว" },
            { "title": "น้ำมะพร้าว" },
            { "title": "น้ำเปล่า" },
            { "title": "น้ำผึ้งมะนาว" },
            { "title": "น้ำส้ม" },
            { "title": "นมเย็น" },
            { "title": "โอเลี้ยง" },
            { "title": "แอปเปิ้ลปั่น" },
            { "title": "ชาเขียวปั่น" },
            { "title": "โกโก้ปั่น" },
            { "title": "กาแฟปั่น" },
            { "title": "มิลค์เชค" },
            { "title": "ผลไม้รวมปั่น" },
            { "title": "สับปะรดปั่น" },
            { "title": "สตรอว์เบอร์รี่ปั่น" },
            { "title": "แตงโมปั่น" },
            { "title": "ชาไทยปั่น" },
            { "title": "ผักปั่น" },
            { "title": "ชาเขียวร้อน" },
            { "title": "กาแฟร้อน" },
            { "title": "เก๊กฮวยร้อน" },
            { "title": "น้ำมะนาวร้อน" },
            { "title": "น้ำใบเตยร้อน" },
            { "title": "น้ำชา" },
            { "title": "น้ำเปล่าร้อน" },
            { "title": "น้ำเต้าหู้ร้อน" }
        ]
    },
    {
        title: "location",
        img: "/images/menu/location.png",
        href: "/location",
        list: [
            { "title": "hospital" },
            { "title": "mall" },
            { "title": "park" },
            { "title": "temple" },
            { "title": "grocery" },
        ]
    },
    {
        title: "typetext",
        img: "/images/menu/chat.png",
        href: "/tts",
    },
    {
        title: "favorites",
        img: "/images/menu/heart.png",
        href: "/favorites",
    }
]